### ISSUE TITLE
Improve blindPosition override 

### ISSUE THREAD

**Issue by jonferreira** [alisdairjsmyth/node-red-contrib-blindcontroller#22]
Hi,

I'm finally adding blindPosition "overrides, as in when someone manually changes the blind position, support on my node-red logic and noticed a few things that could be improved in my humble opinion:

1. No support for a "reset" message

Once one sets a "manual position" it will be forced to *wait* for it to time out. An example where I *don't* want this to happen is when there's a "override" in place and it's time to close the blinds - the blind won't close until the expiry date runs out.
I'd recommend adding support for a "reset" message that would delete blind.blindPositionExpiry, e.g 
message.topic = "blindPosition";
msg.reset = true;

2. expiryperiod is set on the Blind node itself and there's no option to set expiryperiod within the blindPosition message itself. I'd suggest adding support for:
message.topic = "blindPosition";
msg.expiryperiod = 2;

Which would override the expiryperiod set on the Blind node. It could also be used to replace 1. by setting msg.expiryperiod = 0;

3. expiryperiod is set with hours so you can't set a 30 min expiry period for example. would it be possible to change this to minutes? alternatively handle decimal places better so that 1.5 is translated to:

expiryTimestamp.setHours(expiryTimestamp.getHours() + 1);
expiryTimestamp.setMinutes(expiryTimestamp.getMinutes() + 30);

4. on a blindPosition message "channel" is required but I'm not sure why. if you're sending a blindPosition message directly to a blind node I don't see the need for this at all. Of course it would be necessary if you're using BlindControllerWithoutConfig but that would make "channel" optional

I'm happy to work on these and make a pull request if you're interested, just wanted to know your opinion first

**Comment by jonferreira** [comment]
https://github.com/jonferreira/node-red-contrib-blindcontroller/blob/master/blindcontroller/blindcontroller.js

Here's a quick proof of concept that answers 1, 2 and 4 - what do you reckon?

**Comment by alisdairjsmyth** [comment]
All good suggestions. I will have a look at your code tomorrow - time for bed now.

**Comment by alisdairjsmyth** [comment]
**No support for a "reset" message**
I would suggest using a separate message topic.  I think it is clearer what the intent of the message would be, and avoids conditional validation within `validateBlindPositionMsg`.

**expiryperiod is set on the Blind node itself and there's no option to set expiryperiod within the blindPosition message itself.**
If an expiry period is set within the `blindPosition` message it should only apply to the current position, the expiry period on the blind should not change.  The blind expiry period would be applied for subsequent `blindPosition` messages which do not include an override.

A zero expiry period should not be treated as a reset.  It will set a position which has an immediate expiry.

** expiryperiod is set with hours so you can't set a 30 min expiry period for example. would it be possible to change this to minutes? alternatively handle decimal places better so that 1.5 **
I think it clearer to express the expiry as a number of minutes.

** on a blindPosition message "channel" is required but I'm not sure why. **
It should be mandatory for BlindControllerWithoutConfig.

**Comment by jonferreira** [comment]
**I would suggest using a separate message topic.**

OK so something like this?

```
msg.topic = "blindPositionReset"
msg.payload = true
```

**If an expiry period is set within the blindPosition message it should only apply to the current position, the expiry period on the blind should not change**

Yes agree and that's what I'm already doing...

**I think it clearer to express the expiry as a number of minutes.**

Completely agree but that also means that anyone currently using expiry (in hours) will have to update this value to minutes - I'm OK with that though!

**It should be mandatory for BlindControllerWithoutConfig.**

Yes but it's not needed for the BlindControllerWithConfig so how to handle this with only a single validateBlindPositionMsg?

What do you need me to do ? Want me to make a new PR with the above changes or will you handle it yourself?

**Comment by alisdairjsmyth** [comment]
I missed the fact you had submitted a Pull Request.  I will have a look.

**Comment by jonferreira** [comment]
No problem, I can make the changes mentioned - dedicated topic for reset and change expiry from hour to minute - if you want and make another PR

**Comment by jonferreira** [comment]
@alisdairjsmyth did a few more commits to match what we discussed, let me know what you think

**Comment by jonferreira** [comment]
thanks for the pull @alisdairjsmyth 

what do you think about adding expiry time onto the node status message? I could use a quick way to see when the manual set position will expire

**Comment by alisdairjsmyth** [comment]
Is the node-red editor the UI you would use to enquire on this?  When I originally added this feature, I integrated it with SmartThings and used the SmartThings App to make manual adjustments. I would have used the SmartThings App to view the expiry timestamp rather than the node-red editor.

**Comment by jonferreira** [comment]
Yes it's a long overdue project :)
